Adds poll command (a second time because this one passes tests)
stevebot-project/steve pull request #41
Opened 2020-06-18 23:03 UTC by BenSegal855

**Describe this PR and why it should be merged:**
This pull requests adds a simple poll command (with alias vote). Running the command will place the first argument at the top of the returned message in bold. It will then put the other arguments (anywhere from two the ten others) under the first with number emojis in front of them. The first arg is the question or topic to be voted on. The next are the options that can be chosen. After sending the message, reactions are then added for the appropriate number of options.
**Status**
- [ ] This PR has been tested and complies with this project's ESLint rules
- [ ] This PR adds/modifes a command
- [ ] The `examples` and `helpUsage` options have been created/updated accordingly

**Semantic Versioning**
- [ ] This PR features bug fixes, or only style changes/refactorings, or no code changes
- [ ] This PR adds features for users
- [ ] This PR switches this project to a new a new Discord API library/new Discord.js framework

2020-10-27 11:32 UTC, jwford requested changes
i guess my main concern is that if we're going to have a poll comand, i'd like some way to for him to end the poll and tally the votes and announce a winner as well.

2020-10-27 11:32 UTC, jwford commented on src/commands/Fun/Random/poll.ts
> +	}
the description and extended help need to be internationalized, and helpUsage is unnecessary now. you can look at other commands and the en-US.ts language file to see how that should be done

2020-10-27 11:32 UTC, jwford commented on src/commands/Fun/Random/poll.ts
> +			return msg.channel.send(`You have too many choices! The max is 10!`);
also needs to be internationalized

2020-10-27 15:30 UTC, BenSegal855 commented
> i guess my main concern is that if we're going to have a poll comand, i'd like some way to for him to end the poll and tally the votes and announce a winner as well.

Would you want some kind of configurable length before the poll ends or just an arbitrary five or so minutes for every poll?

2020-10-27 15:34 UTC, jwford commented
> > i guess my main concern is that if we're going to have a poll comand, i'd like some way to for him to end the poll and tally the votes and announce a winner as well.
> 
> Would you want some kind of configurable length before the poll ends or just an arbitrary five or so minutes for every poll?

configurable, preferably

2020-10-27 15:41 UTC, BenSegal855 commented
> > > i guess my main concern is that if we're going to have a poll comand, i'd like some way to for him to end the poll and tally the votes and announce a winner as well.
> 
> > 
> 
> > Would you want some kind of configurable length before the poll ends or just an arbitrary five or so minutes for every poll?
> 
> 
> 
> configurable, preferably

So command syntax being something like `s;poll duration|question|choice1|choice2|...` and than after the duration a message would be sent saying something along these lines `choice1 has won question with x votes`

2021-02-10 00:06 UTC, BenSegal855 commented
Closing for now and I will be re-doing this code pretty much from the ground up Soon:tm:

2021-02-10 00:06 UTC, closed without merging